const terapias = [
    {
        id: 10,
        producto: "osteopatia",
        precio: 3300,
        descripcion: "especializacion de la kinesiologia",
        categoría: "terapia manual",
        oferta: true,
        img: "multimedia/osteopatia.jpg",
    },
    {
        id: 04,
        producto: "kinesiologia",
        precio: 1800,
        descripcion: "rehabilitacion",
        categoría: "terapia manual",
        oferta: false,
        img: "multimedia/entradafrente.jpg",
    },
    {
        id: 03,
        producto: "depilacion definitiva",
        precio: 2500,
        descripcion: "estetica",
        categoría: "aparatologia",
        oferta: false,
        img: "multimedia/depilacion.jpeg",
    },
    {
        id: 05,
        producto: "drenaje linfativo",
        precio: 3300,
        descripcion: "masaje depletivo",
        categoría: "terapia manual",
        oferta: false,
        img: "multimedia/drenaje.jpg",
    },
    {
        id: 02,
        producto: "masaje descontracturante",
        precio: 2200,
        descripcion: "contracturas musculares",
        categoría: "terapia manual",
        oferta: false,
        img: "multimedia/saladeespera.jpg",
    },
    {
        id: 06,
        producto: "masajes reductores",
        precio: 2200,
        descripcion: "estetica",
        categoría: "terapia manual",
        oferta: false,
        img: "multimedia/reductores.jpg",
    },
    {
        id: 07,
        producto: "vela velvet",
        precio: 2200,
        descripcion: "trabajo para tejido adiposo",
        categoría: "aparatologia",
        oferta: false,
        img: "multimedia/reductores.jpg",
    },
    {
        id: 11,
        producto: "limpieza facial",
        precio: 2200,
        descripcion: "estetica",
        categoría: "terapia manual",
        oferta: false,
        img: "multimedia/entradalat.jpg",
    },
    {
        id: 09,
        producto: "terapia postural activa",
        precio: 3600,
        descripcion: "ejercicio postural",
        categoría: "rehabilitacion",
        oferta: false,
        img: "multimedia/tpa.jpg",
    },
    {
        id: 1,
        producto: "reeducacion postural global",
        precio: 3300,
        descripcion: "terapia postural",
        categoría: "terapia manual",
        oferta: false,
        img: "multimedia/rpg.jpg",
    },
    {
        id: 08,
        producto: "yoga",
        precio: 4100,
        descripcion: "ejercicio fisico",
        categoría: "ejercicio",
        oferta: false,
        img: "multimedia/yoga.jpg",
    },
    {
        id: 12,
        producto: "puncion seca",
        precio: 3300,
        descripcion: "terapia agujas",
        categoría: "terapia manual",
        oferta: true,
        img: "multimedia/entradalat.jpg",
    },
    {
        id: 15,
        producto: "ventosas",
        precio: 3300,
        descripcion: "trabajo corporal con ventosas",
        categoría: "terapia manual",
        oferta: false,
        img: "multimedia/entradalat.jpg",
    },
    {
        id: 14,
        producto: "rehabilitacion atm",
        precio: 3300,
        descripcion: "problemas en boca",
        categoría: "terapia manual",
        oferta: false,
        img: "multimedia/atm.jpg",
    },
    {
        id: 13,
        producto: "tratamiento paralisis facial",
        precio: 2200,
        descripcion: "problema neruologico",
        categoría: "terapia manual",
        oferta: false,
        img: "multimedia/paralisisFacial.jpg",
    }
]

